import { expect, test } from '@playwright/test'

test('a table creates a character, crosses into the opening scene, and plays', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Campaign name').fill('The Salt Road')
  await page.getByLabel('Your name').fill('Mara')
  await page.getByRole('button', { name: 'Open the table' }).click()
  await page.getByRole('button', { name: 'I saved my seat key' }).click()

  await page.getByRole('button', { name: 'World' }).click()
  const world = page.getByRole('dialog', { name: 'Campaign opening' })
  await world.getByLabel('What is this campaign about?').fill('For seven nights, a drowned town returns beneath a moonless sky.')
  await world.getByRole('button', { name: 'Draft a playable opening' }).click()
  await world.getByRole('button', { name: 'Establish campaign foundation' }).click()
  await expect(world.getByText('Campaign foundation established. The table now has somewhere to begin.')).toBeVisible()
  await world.getByRole('button', { name: 'Close campaign opening' }).click()

  await page.getByRole('button', { name: 'Character', exact: true }).click()
  const character = page.getByRole('dialog', { name: 'Your character' })
  await character.getByRole('button', { name: 'Offer three lives from this world' }).click()
  await expect(character.getByRole('heading', { name: 'Three lives already in motion' })).toBeVisible()
  await character.getByRole('button', { name: /Iria Voss/ }).click()
  await expect(character.getByLabel('Name')).toHaveValue('Iria Voss')
  await character.getByRole('button', { name: 'Take your seat' }).click()
  await expect(character.getByText('Iria Voss has taken a seat at the table.')).toBeVisible()
  await character.getByRole('button', { name: 'Close character folio' }).click()

  const partySeat = page.locator('.party-list .player-row')
  await expect(partySeat.getByText('Iria Voss')).toBeVisible()
  await expect(partySeat.getByText('Mara')).toBeVisible()

  await page.getByRole('button', { name: 'Scene', exact: true }).click()
  const scene = page.getByRole('dialog', { name: 'Scene at the table' })
  await expect(scene.getByLabel('The moment')).toHaveValue('The first toll')
  await expect(scene.getByRole('button', { name: /Iria Voss/ })).toHaveAttribute('aria-pressed', 'true')
  await scene.getByLabel('What demands the first choice?').fill('The rope pulls taut in Iria’s hand. Who cuts it?')
  await scene.getByRole('textbox', { name: 'Clues or discoveries 1', exact: true }).fill('The rope was cut once before, then carefully spliced.')
  await scene.getByRole('textbox', { name: 'Likely complications 1', exact: true }).fill('The Salvagers mistake hesitation for surrender.')
  await scene.getByRole('textbox', { name: 'Questions for the session 1', exact: true }).fill('Who rang the bell before the town returned?')
  await scene.getByRole('button', { name: 'Save preparation' }).click()
  await expect(scene.getByText('Session preparation saved as revision 0.')).toBeVisible()
  await scene.getByRole('button', { name: 'Begin play' }).click()
  await expect(page.getByRole('heading', { name: 'The first toll' })).toBeVisible()
  await expect(page.getByText('The scene opens')).toBeVisible()
  await expect(page.getByText('The rope pulls taut in Iria’s hand. Who cuts it?')).toBeVisible()
  await page.getByLabel('Message in-character').fill('The bell is awake.')
  await page.getByRole('button', { name: 'Send message' }).click()
  const message = page.locator('.message').last()
  await expect(message.getByText('Iria Voss')).toBeVisible()
  await expect(message.getByText('Mara')).toBeVisible()
  await expect(message.getByText('The bell is awake.')).toBeVisible()

  await page.getByRole('button', { name: 'Scene', exact: true }).click()
  const activeScene = page.getByRole('dialog', { name: 'Scene at the table' })
  await expect(activeScene.getByText('Behind the screen')).toBeVisible()
  await expect(activeScene.getByText('The rope was cut once before, then carefully spliced.')).toBeVisible()
  await activeScene.getByLabel('What is true because this scene happened?').fill('Iria cuts the rope and the bell cracks.')
  await activeScene.getByRole('button', { name: 'Record fallout' }).click()
  await activeScene.getByRole('button', { name: /Bell Square/ }).click()
  await activeScene.getByLabel('What is true now?').fill('Bell Square lies open to the drowned archive below.')
  await activeScene.getByLabel('What pressure remains?').fill('The Salvagers will arrive before dawn.')
  await activeScene.getByRole('button', { name: 'Keep a discovery' }).click()
  const discovery = activeScene.locator('.scene-discoveries article')
  await discovery.getByRole('button', { name: 'npc', exact: true }).click()
  await discovery.getByLabel('Name').fill('Sister Corda')
  await discovery.getByLabel('What is their place in the world?').fill('Keeper of the submerged archive.')
  await discovery.getByLabel('What do they want?').fill('Recover the name the sea took from her.')
  await discovery.getByLabel('What can they offer or threaten?').fill('A dry road through the drowned streets.')
  await activeScene.getByRole('button', { name: 'Resolve this scene' }).click()
  await expect(page.getByText('The scene resolves')).toBeVisible()
  await expect(page.getByText('Iria cuts the rope and the bell cracks.')).toBeVisible()

  await page.getByRole('button', { name: 'World' }).click()
  const movingWorld = page.getByRole('dialog', { name: 'Campaign opening' })
  await expect(movingWorld.getByRole('heading', { name: 'World in motion' })).toBeVisible()
  await expect(movingWorld.getByText('Bell Square lies open to the drowned archive below.')).toBeVisible()
  await expect(movingWorld.getByText('The Salvagers will arrive before dawn.')).toBeVisible()
  await expect(movingWorld.getByRole('heading', { name: 'Entered through play' })).toBeVisible()
  await expect(movingWorld.getByRole('heading', { name: 'Sister Corda' })).toBeVisible()
  await expect(movingWorld.getByText('First entered the ledger in “The first toll”')).toBeVisible()
  await movingWorld.getByLabel('What the players are stepping into').fill('The drowned town has opened its archive to the living.')
  await movingWorld.getByRole('button', { name: 'Save campaign revision' }).click()
  await expect(movingWorld.getByText('Campaign foundation saved as revision 1.')).toBeVisible()
  await expect(movingWorld.getByRole('heading', { name: 'Sister Corda' })).toBeVisible()
  await movingWorld.getByRole('button', { name: 'Close campaign opening' }).click()

  await page.getByRole('button', { name: 'Scene', exact: true }).click()
  const nextScene = page.getByRole('dialog', { name: 'Scene at the table' })
  await expect(nextScene.getByText('Pressure still moving')).toBeVisible()
  await nextScene.getByRole('button', { name: 'Carry into the stakes' }).click()
  await expect(nextScene.getByLabel('What changes if nobody acts')).toHaveValue(/The Salvagers will arrive before dawn./)
  await nextScene.getByRole('button', { name: 'Close scene folio' }).click()

  await page.getByRole('button', { name: 'Character', exact: true }).click()
  const aftermath = page.getByRole('dialog', { name: 'Your character' })
  await expect(aftermath.getByRole('heading', { name: 'What has happened to Iria Voss?' })).toBeVisible()
  await expect(aftermath.getByRole('button', { name: /Sister Corda/ })).toBeVisible()
  await expect(aftermath.locator('.character-choices').nth(2).getByRole('button', { pressed: true })).toHaveCount(1)
  await aftermath.getByRole('button', { name: /The first toll/ }).click()
  await aftermath.getByLabel('Why is the character different?').fill('The cracked bell answered in her brother’s voice.')
  await aftermath.getByLabel('A belief others can challenge').fill('Every broken thing can answer.')
  await aftermath.getByRole('button', { name: 'Keep this revision' }).click()
  await expect(aftermath.getByText('Revision 1 is now at the table.')).toBeVisible()
  await expect(aftermath.getByRole('heading', { name: 'How the character has changed' })).toBeVisible()
  await expect(aftermath.getByText('The cracked bell answered in her brother’s voice.')).toBeVisible()
  await expect(aftermath.getByText('After “The first toll”')).toBeVisible()
})
