import { expect, test } from '@playwright/test'

test('a table creates a character, crosses into the opening scene, and plays', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Campaign name').fill('The Salt Road')
  await page.getByLabel('Your name').fill('Mara')
  await page.getByRole('button', { name: 'Open the table' }).click()
  await page.getByRole('button', { name: 'I saved my seat key' }).click()

  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: 'Search', exact: true })).toBeHidden()
  await page.getByRole('button', { name: 'Open table tools' }).click()
  const tools = page.getByRole('dialog', { name: 'Table tools' })
  await expect(tools.getByRole('button', { name: /Character/ })).toBeVisible()
  await expect(tools.getByRole('button', { name: /Scene/ })).toBeVisible()
  await expect(tools.getByRole('button', { name: /World/ })).toBeVisible()
  await expect(tools.getByRole('button', { name: /Invite players/ })).toBeVisible()
  await tools.getByRole('complementary').getByRole('button', { name: 'Close table tools' }).click()
  await page.setViewportSize({ width: 1280, height: 720 })

  await expect(page.getByText('Give the campaign somewhere to begin')).toBeVisible()
  await page.getByRole('button', { name: 'Create the campaign opening' }).click()
  const world = page.getByRole('dialog', { name: 'Campaign opening' })
  await world.getByLabel('What is this campaign about?').fill('For seven nights, a drowned town returns beneath a moonless sky.')
  await world.getByRole('button', { name: 'Draft a playable opening' }).click()
  await world.getByRole('button', { name: 'Establish campaign foundation' }).click()
  await expect(world.getByText('Campaign foundation established. The table now has somewhere to begin.')).toBeVisible()
  await world.getByRole('button', { name: 'Close campaign opening' }).click()

  await expect(page.getByText('Bring the first character to the table')).toBeVisible()
  await page.getByRole('button', { name: 'Create a character' }).click()
  const character = page.getByRole('dialog', { name: 'Your character' })
  await character.getByRole('button', { name: 'Offer three lives from this world' }).click()
  await expect(character.getByRole('heading', { name: 'Three lives already in motion' })).toBeVisible()
  await character.getByRole('button', { name: /Iria Voss/ }).click()
  await expect(character.getByLabel('Name')).toHaveValue('Iria Voss')
  await character.getByRole('button', { name: 'Take your seat' }).click()
  await expect(character.getByText('Iria Voss has taken a seat at the table.')).toBeVisible()
  await character.getByRole('button', { name: 'Close character folio' }).click()

  const partySeat = page.locator('.party-list .player-row')
  await expect(partySeat.getByText('Iria Voss')).toBeVisible()
  await expect(partySeat.getByText('Mara')).toBeVisible()

  await expect(page.getByText('Frame the opening scene')).toBeVisible()
  await page.getByRole('button', { name: 'Build the first session' }).click()
  const scene = page.getByRole('dialog', { name: 'Scene at the table' })
  await expect(scene.getByLabel('The moment')).toHaveValue('The first toll')
  await expect(scene.getByRole('button', { name: /Iria Voss/ })).toHaveAttribute('aria-pressed', 'true')
  await expect(scene.getByText('4 things before this scene can be saved')).toBeVisible()
  await expect(scene.getByRole('button', { name: 'Begin play' })).toBeDisabled()
  await scene.getByLabel('What demands the first choice?').fill('The rope pulls taut in Iria’s hand. Who cuts it?')
  await scene.getByRole('textbox', { name: 'Clues or discoveries 1', exact: true }).fill('The rope was cut once before, then carefully spliced.')
  await scene.getByRole('textbox', { name: 'Likely complications 1', exact: true }).fill('The Salvagers mistake hesitation for surrender.')
  await scene.getByRole('textbox', { name: 'Questions for the session 1', exact: true }).fill('Who rang the bell before the town returned?')
  await expect(scene.getByText('Ready to save')).toBeVisible()
  await scene.getByRole('button', { name: 'Save preparation' }).click()
  await expect(scene.getByText('Session preparation saved as revision 0.')).toBeVisible()
  await expect(scene.getByText('The preparation is durable. Begin play when everyone is ready.')).toBeVisible()
  await expect(scene.getByRole('button', { name: 'Begin play' })).toBeEnabled()
  await scene.getByRole('button', { name: 'Begin play' }).click()
  await expect(page.getByRole('heading', { name: 'The first toll' })).toBeVisible()
  await expect(page.getByText('The scene opens')).toBeVisible()
  await expect(page.getByText('The rope pulls taut in Iria’s hand. Who cuts it?')).toBeVisible()
  await page.getByLabel('Message in-character').fill('The bell is awake.')
  await page.getByRole('button', { name: 'Send message' }).click()
  const message = page.locator('.message').last()
  await expect(message.getByText('Iria Voss')).toBeVisible()
  await expect(message.getByText('Mara')).toBeVisible()
  await expect(message.getByText('The bell is awake.')).toBeVisible()

  await page.getByRole('button', { name: 'Scene', exact: true }).click()
  const activeScene = page.getByRole('dialog', { name: 'Scene at the table' })
  await expect(activeScene.getByText('Behind the screen')).toBeVisible()
  await expect(activeScene.getByText('The rope was cut once before, then carefully spliced.')).toBeVisible()
  await activeScene.getByLabel('What does the table need?').fill('Someone who knows why the archive opened.')
  await activeScene.getByRole('button', { name: 'Draft one' }).click()
  await expect(activeScene.getByText('Private npc draft')).toBeVisible()
  await activeScene.getByLabel('Name', { exact: true }).fill('Brother Vey of the Salt Archive')
  await activeScene.getByRole('button', { name: 'Keep in campaign' }).click()
  await expect(activeScene.getByText('Brother Vey of the Salt Archive is now in the campaign.')).toBeVisible()
  await expect(activeScene.getByText('Kept from this scene')).toBeVisible()
  await activeScene.getByLabel('What is true because this scene happened?').fill('Iria cuts the rope and the bell cracks.')
  await activeScene.getByRole('button', { name: 'Record fallout' }).click()
  await activeScene.getByRole('button', { name: /Bell Square/ }).click()
  await activeScene.getByLabel('Who controls or claims it?').fill('The party holds the opened stair.')
  await activeScene.getByLabel('Current danger').fill('The drowned archive lies exposed below.')
  await activeScene.getByLabel('What pressure remains?').fill('The Salvagers will arrive before dawn.')
  await activeScene.getByRole('button', { name: 'Keep a discovery' }).click()
  const discovery = activeScene.locator('.scene-discoveries article')
  await discovery.getByRole('button', { name: 'npc', exact: true }).click()
  await discovery.getByLabel('Name').fill('Sister Corda')
  await discovery.getByLabel('What is their place in the world?').fill('Keeper of the submerged archive.')
  await discovery.getByLabel('What do they want?').fill('Recover the name the sea took from her.')
  await discovery.getByLabel('What can they offer or threaten?').fill('A dry road through the drowned streets.')
  await activeScene.getByRole('button', { name: 'Resolve this scene' }).click()
  await expect(page.getByText('The scene resolves')).toBeVisible()
  await expect(page.getByText('Iria cuts the rope and the bell cracks.')).toBeVisible()

  await page.getByRole('button', { name: 'World' }).click()
  const movingWorld = page.getByRole('dialog', { name: 'Campaign opening' })
  await expect(movingWorld.getByRole('heading', { name: 'World in motion' })).toBeVisible()
  await expect(movingWorld.getByText('Ownership: The party holds the opened stair. · Danger: The drowned archive lies exposed below.')).toBeVisible()
  await expect(movingWorld.getByText('The party holds the opened stair.', { exact: true })).toBeVisible()
  await expect(movingWorld.getByText('The Salvagers will arrive before dawn.', { exact: true }).first()).toBeVisible()
  await expect(movingWorld.getByRole('heading', { name: 'Entered through play' })).toBeVisible()
  await expect(movingWorld.getByRole('heading', { name: 'Sister Corda' })).toBeVisible()
  await expect(movingWorld.getByRole('heading', { name: 'Brother Vey of the Salt Archive' })).toBeVisible()
  await expect(movingWorld.getByText('First entered the ledger in “The first toll”')).toHaveCount(2)
  await movingWorld.getByLabel('What the players are stepping into').fill('The drowned town has opened its archive to the living.')
  await movingWorld.getByRole('button', { name: 'Save campaign revision' }).click()
  await expect(movingWorld.getByText('Campaign foundation saved as revision 3.')).toBeVisible()
  await expect(movingWorld.getByRole('heading', { name: 'Sister Corda' })).toBeVisible()
  await movingWorld.getByRole('button', { name: 'Close campaign opening' }).click()

  await page.getByRole('button', { name: 'Scene', exact: true }).click()
  const nextScene = page.getByRole('dialog', { name: 'Scene at the table' })
  await expect(nextScene.getByRole('heading', { name: 'Draft what follows from play' })).toBeVisible()
  await nextScene.getByRole('button', { name: 'Draft from play' }).click()
  const continuation = nextScene.locator('.scene-continuation')
  await expect(continuation.getByText('Private continuation draft')).toBeVisible()
  await expect(continuation.getByRole('heading', { name: 'Before the salvagers arrive' })).toBeVisible()
  await expect(continuation.getByText('The Salvagers will arrive before dawn.')).toBeVisible()
  await continuation.getByRole('button', { name: 'Use as preparation' }).click()
  await expect(nextScene.getByText('The continuation is in the preparation folio.')).toBeVisible()
  await expect(nextScene.getByLabel('The moment')).toHaveValue('Before the salvagers arrive')
  await expect(nextScene.getByLabel('What changes if nobody acts')).toHaveValue('The drowned archive will be stripped bare before dawn.')
  await expect(nextScene.getByText('Pressure still moving')).toBeVisible()
  await nextScene.getByRole('button', { name: 'Carry into the stakes' }).click()
  await expect(nextScene.getByLabel('What changes if nobody acts')).toHaveValue(/The Salvagers will arrive before dawn./)
  await nextScene.getByRole('button', { name: 'Save preparation' }).click()
  await expect(nextScene.getByText('Session preparation saved as revision 0.')).toBeVisible()
  await nextScene.getByRole('button', { name: 'Close scene folio' }).click()

  await page.getByRole('button', { name: 'Character', exact: true }).click()
  const aftermath = page.getByRole('dialog', { name: 'Your character' })
  await expect(aftermath.getByRole('heading', { name: 'What has happened to Iria Voss?' })).toBeVisible()
  await expect(aftermath.getByRole('button', { name: /Sister Corda/ })).toBeVisible()
  await expect(aftermath.locator('.character-choices').nth(2).getByRole('button', { pressed: true })).toHaveCount(1)
  await aftermath.getByRole('button', { name: /The first toll/ }).click()
  await aftermath.getByLabel('Why is the character different?').fill('The cracked bell answered in her brother’s voice.')
  await aftermath.getByLabel('A belief others can challenge').fill('Every broken thing can answer.')
  await aftermath.getByRole('button', { name: 'Keep this revision' }).click()
  await expect(aftermath.getByText('Revision 1 is now at the table.')).toBeVisible()
  await expect(aftermath.getByRole('heading', { name: 'How the character has changed' })).toBeVisible()
  await expect(aftermath.getByText('The cracked bell answered in her brother’s voice.')).toBeVisible()
  await expect(aftermath.getByText('After “The first toll”')).toBeVisible()
})
