import { expect, test } from '@playwright/test'

test('a GM edits and publishes a recap and resolves continuity inline', async ({ browser, page }) => {
  await page.goto('/')
  await page.getByLabel('Campaign name').fill('The Old Road')
  await page.getByLabel('Your name').fill('Mara')
  await page.getByRole('button', { name: 'Open the table' }).click()
  await page.getByRole('button', { name: 'I saved my seat key' }).click()
  await page.getByRole('button', { name: 'Invite players' }).click()
  const invitation = page.getByRole('dialog', { name: 'The Old Road' })
  const inviteUrl = await invitation.locator('.invite-link code').innerText()
  const guestContext = await browser.newContext()
  const guest = await guestContext.newPage()
  await guest.goto(inviteUrl)
  await guest.getByLabel('Your name').fill('Theo')
  await guest.getByRole('button', { name: 'Join the table' }).click()
  await guest.getByRole('button', { name: 'I saved my seat key' }).click()
  await invitation.getByRole('complementary').getByLabel('Close invitation').click()

  await page.getByLabel('Message fireside').fill('We crossed the old gate at dawn.')
  await page.getByRole('button', { name: 'Send message' }).click()
  await page.getByRole('button', { name: 'Canon' }).click()
  const ledger = page.getByRole('dialog', { name: 'Living canon ledger' })
  await ledger.getByLabel('Session title').fill('Crossing the old gate')
  await ledger.getByRole('button', { name: 'Close session' }).click()

  await ledger.getByRole('button', { name: 'Prepare draft' }).click()
  await expect(ledger.getByText('The party crossed the old gate.', { exact: true })).toBeVisible()
  await ledger.getByRole('button', { name: 'Edit draft' }).click()
  await ledger.getByLabel('For the table').fill('The party crossed the old gate at dawn.')
  await ledger.getByLabel('Private GM notes').fill('A watcher followed them beyond the gate.')
  await ledger.getByRole('button', { name: 'Save draft revision' }).click()
  await expect(ledger.getByText('Revision 1', { exact: true })).toBeVisible()
  await ledger.getByRole('button', { name: 'History' }).click()
  await expect(ledger.getByText('The party crossed the old gate at dawn.', { exact: true }).first()).toBeVisible()
  await ledger.getByRole('button', { name: 'Publish recap to campaign' }).click()
  await expect(ledger.getByText('published', { exact: true })).toBeVisible()

  await ledger.getByRole('button', { name: 'Prepare brief' }).click()
  const continuity = ledger.getByLabel('Session continuity')
  await expect(continuity.getByText('The road beyond remains unexplored.', { exact: true })).toBeVisible()
  await continuity.getByRole('button', { name: 'Useful', exact: true }).click()
  const evaluation = ledger.getByLabel('AI evaluation ledger')
  await expect(evaluation.getByText('e2e:continuity-v1', { exact: true })).toBeVisible()
  await expect(evaluation.locator('.evaluation-verdict').filter({ hasText: 'Continuity verdicts' }).getByText('100%', { exact: true })).toBeVisible()
  await continuity.getByRole('button', { name: 'Resolve' }).click()
  await continuity.getByLabel('Reason').fill('The party mapped the road.')
  await continuity.getByRole('button', { name: 'Record status' }).click()
  await expect(continuity.getByText('resolved', { exact: true })).toBeVisible()
  await expect(continuity.getByText(/The party mapped the road/)).toBeVisible()

  await guest.getByRole('button', { name: 'Canon' }).click()
  const guestLedger = guest.getByRole('dialog', { name: 'Living canon ledger' })
  await expect(guestLedger.getByText('The party crossed the old gate at dawn.', { exact: true })).toBeVisible()
  await expect(guestLedger.getByText('A watcher followed them beyond the gate.', { exact: true })).toHaveCount(0)
  await guestContext.close()

  await ledger.getByRole('button', { name: 'Close canon ledger' }).last().click()
  await page.getByRole('button', { name: 'Table tools' }).click()
  const intelligence = page.getByRole('dialog', { name: 'Campaign intelligence' })
  await intelligence.getByRole('button', { name: 'Choose passages' }).click()
  await intelligence.locator('.rule-compiler input[type="checkbox"]').first().check()
  await intelligence.getByRole('button', { name: 'Compile 1 selected' }).click()
  await expect(intelligence.getByText('e2e:intelligence-v1', { exact: true }).first()).toBeVisible()
  await intelligence.getByLabel('Table ruling').fill('Careful searches gain advantage after a deliberate approach.')
  await intelligence.getByLabel('Reason for this decision').fill('Agreed after crossing the gate.')
  await intelligence.getByRole('button', { name: 'Accept ruling' }).click()
  await expect(intelligence.getByText('Accepted with 1 edit', { exact: true })).toBeVisible()
  await expect(intelligence.locator('.rule-ledger').getByRole('heading', { name: 'Lantern searches' })).toBeVisible()
  await intelligence.getByRole('button', { name: 'History' }).click()
  await expect(intelligence.getByText('Revision 0 · active', { exact: true })).toBeVisible()
  await intelligence.getByLabel('Faction').fill('Moth Court')
  await intelligence.getByLabel('Goal').fill('Open the western archive')
  await intelligence.getByRole('button', { name: 'Add clock' }).click()
  await expect(intelligence.getByRole('heading', { name: 'Moth Court' })).toBeVisible()
  await intelligence.getByRole('button', { name: 'Propose next motion' }).click()
  await expect(intelligence.getByText('The watchers move toward the old gate.', { exact: true })).toBeVisible()
  await intelligence.getByRole('button', { name: 'Accept exact change' }).click()
  await expect(intelligence.getByText('1/6', { exact: true })).toBeVisible()
})
